// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ProjetoDDD.Data.Context;

namespace ProjetoDDD.Data.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.4-servicing-10062")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("ProjetoDDD.Domain.Entidades.Aluno", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Email");

                    b.Property<int?>("MateriaId");

                    b.Property<string>("Nome");

                    b.Property<string>("Ra");

                    b.Property<string>("Senha");

                    b.HasKey("Id");

                    b.HasIndex("MateriaId");

                    b.ToTable("Alunos");
                });

            modelBuilder.Entity("ProjetoDDD.Domain.Entidades.Materia", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("NomeMateria");

                    b.HasKey("Id");

                    b.ToTable("Materia");
                });

            modelBuilder.Entity("ProjetoDDD.Domain.Entidades.Professor", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Email");

                    b.Property<int?>("MateriaId");

                    b.Property<string>("Nome");

                    b.Property<double>("Salario");

                    b.Property<string>("Senha");

                    b.HasKey("Id");

                    b.HasIndex("MateriaId");

                    b.ToTable("Professor");
                });

            modelBuilder.Entity("ProjetoDDD.Domain.Entidades.Aluno", b =>
                {
                    b.HasOne("ProjetoDDD.Domain.Entidades.Materia", "Materia")
                        .WithMany()
                        .HasForeignKey("MateriaId");
                });

            modelBuilder.Entity("ProjetoDDD.Domain.Entidades.Professor", b =>
                {
                    b.HasOne("ProjetoDDD.Domain.Entidades.Materia", "Materia")
                        .WithMany()
                        .HasForeignKey("MateriaId");
                });
#pragma warning restore 612, 618
        }
    }
}
